name: Download latest temporary housing monthly report
#
on:
  schedule:
    - cron: '12 2 3,8,13 * *'
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v5
    - name: Fetch latest data
      run: |-
        curl -L -o ./temporary_housing_report_pdfs/temp_temporary_housing_report.pdf \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" \
          -H "Accept: application/pdf,*/*" \
          -H "Referer: https://www.nyc.gov/" \
          https://www.nyc.gov/assets/operations/downloads/pdf/temporary_housing_report.pdf
        python3 rename_temp_housing_report.py
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Downloaded latest Temporary Housing Report PDF"
